name: frontend_loreal
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  bcrypt: ^1.1.3
  cache_manager: ^1.0.0+4
  cupertino_icons: ^1.0.2
  dart_jsonwebtoken: ^2.6.2
  dio: ^5.3.2
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  flutter_easyloading: ^3.0.5
  flutter_expanded_tile: ^0.4.0
  flutter_localization: ^0.2.0
  flutter_localizations:
    sdk: flutter
  flutter_multi_formatter: ^2.2.1
  flutter_riverpod: ^2.0.2
  flutter_secure_storage: ^9.2.2
  flutter_svg: ^2.0.7
  html: ^0.15.1
  http: ^1.1.0
  intl: ^0.19.0
  json_annotation: ^4.7.0
  json_serializable: ^6.3.1
  local_auth: ^2.3.0
  number_text_input_formatter: ^1.0.0+1
  open_file: ^3.3.2
  path_provider: ^2.0.11
  pdf: ^3.8.4
  permission_handler: ^11.1.0
  printing: ^5.9.3
  riverpod_annotation: ^2.1.1
  riverpod_lint: ^2.1.0
  shared_preferences: ^2.2.0
  sqflite: ^2.0.2
  uuid: ^4.4.0

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "lib/assets/icon.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - lib/assets/
    - lib/assets/change_log/
    - lib/assets/lottie/
    - .env

  fonts:
    - family: Dosis
      fonts:
        - asset: lib/fonts/Dosis-Bold.ttf
        - asset: lib/fonts/Dosis-Light.ttf
          style: italic
